SELECT I.SUMMARY AS TASK, IL.NAME AS TASKLIST
FROM ISSUES I, ISSUESLISTS IL
WHERE IL.ID = I.ISSUESLIST_ID;

SELECT I.SUMMARY AS TASK, U.ID AS USER_ID
FROM ISSUES I, USERS U
WHERE I.USER_ID_ASSIGNEDTO = U.ID;

SELECT U.FIRSTNAME, U.LASTNAME, COUNT(*) AS NUMBER_OF_TASKS
FROM ISSUES I, USERS U
WHERE I.USER_ID_ASSIGNEDTO = U.ID
GROUP BY USER_ID_ASSIGNEDTO
HAVING COUNT(*) > 0;

